# Generated by Django 4.1.7 on 2023-03-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(default='Bishkek', max_length=50, verbose_name='City')),
                ('country', models.CharField(default='Kyrgyzstan', max_length=50, verbose_name='Country')),
                ('postal_code', models.CharField(default='720000', max_length=50, verbose_name='Postal Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_addresses',
            },
        ),
    ]
